In [2]:
# coding:utf8

import numpy as np

In [6]:
# 创建一个3 * 3的矩阵，其中元素为0至8)

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

***
## Array Mathematics

Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.

* Task

You are given two integer arrays, A and B of dimensions NxM.
Your task is to perform the following operations:

Add (A + B)

Subtract (A - B)

Multiply (A * B)

Integer Division (A / B)

Mod (A % B)

Power (A ** B)

* Input Format:

The first line contains two space separated integers, N and M.
The next N lines contains M space separated integers of array A.
The following N lines contains M space separated integers of array B.

* Output Format:

Print the result of each operation in the given order under Task.

In [40]:
import numpy
# 接收键盘输入的行、列数，以空格隔开,分别赋值给x、y
x, y = [eval(i) for i in input().strip().split()]
# 分别输入两个数组，均以空格隔开，按照行数控制次数，按照列数控制每次的长度
arr1 = numpy.array([input().split() for i in range(x)], dtype=int)
arr2 = numpy.array([input().split() for i in range(x)], dtype=int)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)


2 3
10 14 19
13 16 11
4 5 6
3 6 8
[[14 19 25]
 [16 22 19]]
[[ 6  9 13]
 [10 10  3]]
[[ 40  70 114]
 [ 39  96  88]]
[[2 2 3]
 [4 2 1]]
[[2 4 1]
 [1 4 3]]
[[    10000    537824  47045881]
 [     2197  16777216 214358881]]


***
## Shape and Reshape

>shape

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

(a) get array dimensions

ndarray.shape

(b) change array dimensions

ndarray.shape = (n,m)

>reshape

The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.
```

* Task

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

* Input Format

A single line of input containing 9 space separated integers.

* Output Format

Print the 3X3 NumPy array.

In [49]:
arr = np.array([eval(i) for i in input().split()])
arr.shape = (3,3)
arr

1 2 3 4 5 6 7 8 9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

***
## Floor, Ceil and Rint

>floor

The tool floor returns the floor of the input element-wise.
The floor of x is the largest integer i where i<=x.

>ceil

The tool ceil returns the ceiling of the input element-wise.
The ceiling of x is the smallest integer i where i<=x.

>rint

The rint tool rounds to the nearest integer of input element-wise.

* Task

You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

* Input Format

A single line of input containing the space separated elements of array A.

* Output Format

On the first line, print the floor of A.
On the second line, print the ceil of A.
On the third line, print the rint of A.

In [54]:
A = np.array([eval(i) for i in input().split()])
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]
