In [63]:
# coding:utf8

# https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

import numpy as np

#### 8-Reverse a vector (first element becomes last) (将数组逆序)

In [2]:
arr = np.arange(50)
arr = arr[::-1]
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 15 - Create a 2d array with 1 on the border and 0 inside (创建2维数组，边界处元素值为1而内部元素值为0)

In [44]:
# Z = np.ones((10,10))
# Z[1:-1,1:-1] = 0
# print(Z)

m,n = [eval(i) for i in input().split()]
size = m*n
arr = np.arange(2,size+2).reshape(m,n)
arr[:]=1
arr[0],arr[-1]=0,0
arr[:,0],arr[:,-1]=0,0
print(arr)

5 6
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


#### 19 - Create a 8x8 matrix and fill it with a checkerboard pattern (创建8x8的2维数组，按照棋盘的黑白相间的格式以1和0交替填充该数组)

In [43]:
# Z = np.zeros((8,8),dtype=int)
# Z[1::2,::2] = 1
# Z[::2,1::2] = 1
# print(Z)

arr = np.zeros(64,dtype=int).reshape(8,8)
for i in range(len(arr)):
    arr[i,i%2::2] = 1
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 70 - Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (现有数组[1，2，3，4，5]，如何构建新数组，在原数组的每两个数之间插入3个连续的0)

In [62]:
# arr = np.array([1,2,3,4,5])
# arr1 = np.zeros((len(arr)-1)*3,int).reshape(len(arr)-1,3)
# new_array = []
# for i in range(len(arr)-1):
#     new_array += [arr[i]]+arr1[i].tolist()
# new_array += [arr[-1]]
# new_array

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z  #原数组切片赋值，改变原数组
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
