In [6]:
# coding:utf8
import numpy as np

In [13]:
# Create a null vector of size 10 (创建一个大小为10的空数组)
arr = np.empty(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# Create a vector with values ranging from 10 to 49 (创建一个元素值为10-49的数组)

arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
# Create a 3x3 identity matrix (创建一个3 * 3大小的单位矩阵)
arr2 = np.eye(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])